spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:h2:mem:auth-server
    driver-class-name: org.h2.Driver
    username: sa
    password:

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/auth-server
          jwk-set-uri: http://localhost:8180/realms/auth-server/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: spring-app
            client-secret: spring-app-secret
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/auth-server
            user-name-attribute: preferred_username

keycloak:
  auth-server-url: http://localhost:8180/realms/auth-server
  realm: auth-server
  resource: spring-app

